# -*- coding: utf-8 -*-
"""Exercício 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hwvuabV47MEojNdIlTapo5P8t5kaPah7
"""

# Validação de Senha: Escreva um programa que valide se uma senha é forte o suficiente. Uma senha é considerada forte se tiver pelo menos oito caracteres,
# contendo pelo menos uma letra maiúscula, uma letra minúscula, um número e um caractere especial. Utilize dicionários para cada tipo de caractéres
# (maiúsculas, minúsculas, números e caractere especial).

def validar_senha(senha):
    # Dicionários para cada tipo de caractere
    caracteres = {
        'maiusculas': 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
        'minusculas': 'abcdefghijklmnopqrstuvwxyz',
        'numeros': '0123456789',
        'especiais': '!@#$%^&*()-_=+[]{}|;:,.<>?/'
    }

    # Verificar se a senha tem pelo menos 8 caracteres
    if len(senha) < 8:
        return False, "A senha deve ter pelo menos 8 caracteres."

    # Verificar a presença de pelo menos um caractere de cada tipo
    tem_maiuscula = any(c in caracteres['maiusculas'] for c in senha)
    tem_minuscula = any(c in caracteres['minusculas'] for c in senha)
    tem_numero = any(c in caracteres['numeros'] for c in senha)
    tem_especial = any(c in caracteres['especiais'] for c in senha)

    # Verificar se há uma sequência de números
    sequencias_invalidas = ["123456", "234567", "345678", "456789", "567890"]
    tem_sequencia_numerica = any(seq in senha for seq in sequencias_invalidas)

    # Senha é forte se tiver pelo menos um de cada tipo de caractere e não tiver sequência de números
    if not tem_maiuscula:
        return False, "A senha precisa ter pelo menos uma letra maiúscula."
    if not tem_minuscula:
        return False, "A senha precisa ter pelo menos uma letra minúscula."
    if not tem_numero:
        return False, "A senha precisa ter pelo menos um número."
    if not tem_especial:
        return False, "A senha precisa ter pelo menos um caractere especial."
    if tem_sequencia_numerica:
        return False, "A senha não pode conter sequências de números como '123456'."

    return True, "A senha é forte."

# Informar ao usuário os requisitos da senha
print("A senha precisa ter pelo menos 8 caracteres, contendo pelo menos uma letra maiúscula, uma letra minúscula, um número e um caractere especial.")
print(" Além disso, a senha não pode conter sequências de números como '123456'.")
# Solicitar senha do usuário até que ele digite uma senha forte
while True:
    senha = input("Digite a senha para validação: ")
    valida, mensagem = validar_senha(senha)
    print(mensagem)
    if valida:
        break

print("Senha válida e forte cadastrada com sucesso!")