# -*- coding: utf-8 -*-
"""Exercício 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDKY_WgEw1S7sAmLVIYB1jfQ1ZfY8l8o
"""

#Escreva uma função em Python que verifica se uma palavra é um palíndromo. Um palíndromo é uma palavra que é lida da mesma forma de trás para frente.
def verifica_palindromo(palavra):
    palavra = palavra.replace(" ", "").lower()
    # Comparar a palavra
    return palavra == palavra[::-1]

# Solicita ao usuário que digite uma palavra
palavra = input("Digite uma palavra para verificar se é um palíndromo: ")

# Verifica se a palavra é um palíndromo e exibe o resultado na tela
if verifica_palindromo(palavra):
    print(f'"{palavra}" é um palíndromo.')
else:
    print(f'"{palavra}" não é um palíndromo.')