# -*- coding: utf-8 -*-
"""Exercício 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sbFjp6VVCUeJa_efJCYmbS3ESq5y3lOu
"""

#Faça um programa, em Python, onde o usuário escolhe um elemento para jogar e o computador escolhe, aleatoriamente, outro elemento.
#O computador deve informar ao usuário qual foi o evento escolhido, informar ao usuário o resultado e quem foi o ganhador da rodada.

import random

# Dicionário com as regras do jogo
regras = {
    "Pedra": ["Tesoura", "Lagarto"],
    "Papel": ["Pedra", "Spock"],
    "Tesoura": ["Papel", "Lagarto"],
    "Lagarto": ["Papel", "Spock"],
    "Spock": ["Tesoura", "Pedra"]
}

def escolher_elemento():
    elementos = list(regras.keys())
    return random.choice(elementos)

def determinar_vencedor(usuario, adversário):
    if usuario == adversário:
        return "Empate"
    elif adversário in regras[usuario]:
        return "Usuário"
    else:
        return "Adversário"

def main():
    print("Bem-vindo ao jogo Pedra-Papel-Tesoura-Lagarto-Spock!")
    elementos = list(regras.keys())

    while True:
        usuario = input("Escolha Pedra, Papel, Tesoura, Lagarto ou Spock: ")
        if usuario in elementos:
            break
        print("Escolha inválida! Tente novamente.")

    adversário = escolher_elemento()
    print(f"O adversário escolheu: {adversário}")

    vencedor = determinar_vencedor(usuario, adversário)

    if vencedor == "Empate":
        print("O jogo empatou!")
    else:
        print(f"O vencedor é: {vencedor}")

    print("\nRegras do jogo:")
    print("Pedra esmaga Tesoura e Lagarto.")
    print("Papel cobre Pedra e refuta Spock.")
    print("Tesoura corta Papel e decapita Lagarto.")
    print("Lagarto envenena Spock e come Papel.")
    print("Spock vaporiza Pedra e quebra Tesoura.")

if __name__ == "__main__":
    main()