# -*- coding: utf-8 -*-
"""Exercício 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iifAe_ceeEUZiq1aHY8vXJgmbcBPz0Zh
"""

#Escreva um programa Python que LEIA UM ARQUIVO .TXT e conte o número de PALAVRAS em um arquivo de texto.

from google.colab import drive
drive.mount('/content/drive', force_remount = False)

import os

cwd = '/content/drive/MyDrive/cursos/Aulas Python 2025'

os.chdir(cwd)

nome_arquivo = input('Digite o nome do arquivo: ')
with open(nome_arquivo, 'r') as arquivo:
  conteudo = arquivo.read()
  palavras = conteudo.split()
  print(f'O arquivo {nome_arquivo} tem {len(palavras)} palavras')